### ISSUE TITLE
Config cannot be saved

### ISSUE THREAD

**Issue by m3m0rex** [GimpArm/hassio-addons#2]
As soon as i try to save my configuration, the default config will be shown and i cannot update the config

**Comment by GimpArm** [comment]
Which config? The one in the hassio UI or the deviceMap.json for the MQTT devices?

**Comment by m3m0rex** [comment]
i am sorry, i meant hassio UI configuration. 
Currently i switched back to the REST API outdated version, cause there i can update the settings

**Comment by GimpArm** [comment]
Just set the mqtt password to anything. Apparently null isn't considered a valid value for an optional parameter. I fixed the default in the config, so if you were to uninstall it, reload the add-on store, then re-install it you'll get "password" as a default value and then it works. Although its just easier if you set it.
