### ISSUE TITLE
standalone version

### ISSUE THREAD

**Issue by smartybox** [GimpArm/hassio-addons#3]
It is not an issue than more a question. Feel free to close the issue directly. 

I use homeassistant in a container only version. Therefore, I cannot use the add-on feature. What is the easiest way to run the bridge? Modify this docker file here that it is not depending on hassio? Would be great to add such an alternative version.

**Comment by GimpArm** [comment]
I'm sorry, I did not see this issue opened until now.

You have two choices, both methods you will need to handle updates yourself.

### Docker
1. Create a file `C:\smartfriends-data\options.json` that is a copy & modified for your network that looks like the appsettings.json from https://github.com/GimpArm/smartfriends-bridge/blob/main/source/SmartFriends.Host/appsettings.json
2. Run the docker container directly on a docker server with a command like:
`docker run -d -p 5001:80 -v C:\smartfriends-data:/data gimparm/amd64-smartfriends-bridge:latest`

OR

### Run Directly
1. Download the latest release binary zip file from the code repository: https://github.com/GimpArm/smartfriends-bridge/releases
2. Install ASP.NET Core Runtime 6.x installed (Windows, Linux, MacOS) https://dotnet.microsoft.com/en-us/download/dotnet/6.0
3. Edit the included `appsettings.json` file.
4. Run the dotnet command `dotnet SmartFriends.Host.dll  --urls=http://0.0.0.0:5001;http://[::]:5001`
