### ISSUE TITLE
Can not install the addon

### ISSUE THREAD

**Issue by MichaelS1955** [GimpArm/hassio-addons#4]
Hi,

I have added the repository but when I try to install it I get this error:
Can't install gimparm/armv7-smartfriends-bridge:3.10: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=3.10&fromImage=gimparm%2Farmv7-smartfriends-bridge&platform=linux%2Farm%2Fv7: Not Found ("manifest for gimparm/armv7-smartfriends-bridge:3.10 not found: manifest unknown: manifest unknown")
I am using Home Assistant =S 10.5 and core version 2023.8.4

Can you help me what is going wrong?

Michael

**Comment by GimpArm** [comment]
Super weird, my release process made a version 3.10 container for every architecture except armv7. The only change to v3.10 was the removal of the entity name from MQTT. So you should be able to run that version just fine still. I'll try to get out the armv7 container asap.

**Comment by MichaelS1955** [comment]
Thank you for the quick response.
Until now I have not tried your add-on. So I have to wait

**Comment by GimpArm** [comment]
I pushed an updated armv7 image. You should be able to install it now.

**Comment by MichaelS1955** [comment]
Thank you, I will install it in the next days

 

Von: GimpArm ***@***.***> 
Gesendet: Samstag, 2. September 2023 10:52
An: GimpArm/hassio-addons ***@***.***>
Cc: MichaelS1955 ***@***.***>; Author ***@***.***>
Betreff: Re: [GimpArm/hassio-addons] Can not install the addon (Issue #4)

 

I pushed an updated armv7 image. You should be able to install it now.
