### ISSUE TITLE
Now status sind update 

### ISSUE THREAD

**Issue by RacerEdge** [GimpArm/hassio-addons#5]
Hello together,

since the  seventh of December I get not status from the Schellenberg devices.
have anyone the same issue or is it only my installation?

i configured the connection with the API.
Remotecontrol is still funktionell. only the status doesn't work.

can anyone help?

thanks in advance

**Comment by GimpArm** [comment]
Are you using REST or MQTT? Also, some models of the rolling shutters do not report position or only do so after you've calibrated it in the official app. So try re-pairing and re-calibrating.

If you post the contents of the /list like http://homeassistant.local:5001/list I can tell you more.

**Comment by RacerEdge** [comment]
I’m using  REST API.

And i have  3 Motors they doesn’t report the position.

But the others does until 7th December.

When I try to request the position in the Terminalwindow, I get the current position.

 

[core-ssh ~]$ curl http://homeassistant:5001/get/16825/position

{

  "Id": 11303,

  "description": "SchellenbergPosition_Adjustable",

  "max": 100,

  "min": 0,

  "precision": 0,

  "step": 1,

  "currentValue": 16

}

[core-ssh ~]$

 

I attach the list and the yaml file.

 

 

Von: GimpArm ***@***.***>
Antworten an: GimpArm/hassio-addons ***@***.***>
Datum: Dienstag, 19. Dezember 2023 um 07:37
An: GimpArm/hassio-addons ***@***.***>
Cc: RacerEdge ***@***.***>, Author ***@***.***>
Betreff: Re: [GimpArm/hassio-addons] Now status sind update (Issue #5)

 

Are you using REST or MQTT? Also, some models of the rolling shutters do not report position or only do so after you've calibrated it in the official app. So try re-pairing and re-calibrating.

If you post the contents of the /list like http://homeassistant.local:5001/list I can tell you more.

**Comment by RacerEdge** [comment]
It must be depend on these updates

 

 
Commits on Dec 7, 2023
Bump actions/setup-python from 4.8.0 to 5.0.0 (#4748)
dependabot[bot] committed 2 weeks ago

Bump getsentry/action-release from 1.4.1 to 1.6.0 (#4747) 
dependabot[bot] committed 2 weeks ago

 
after this update the status doesn’t work

 

 

 

Von: GimpArm ***@***.***>
Antworten an: GimpArm/hassio-addons ***@***.***>
Datum: Dienstag, 19. Dezember 2023 um 07:37
An: GimpArm/hassio-addons ***@***.***>
Cc: RacerEdge ***@***.***>, Author ***@***.***>
Betreff: Re: [GimpArm/hassio-addons] Now status sind update (Issue #5)

 

Are you using REST or MQTT? Also, some models of the rolling shutters do not report position or only do so after you've calibrated it in the official app. So try re-pairing and re-calibrating.

If you post the contents of the /list like http://homeassistant.local:5001/list I can tell you more.

**Comment by GimpArm** [comment]
If you can control it then it is almost certainly the SmartFriends box not reporting the numbers. Check if it works in the official app. Try resetting it up in SmartFriends.

Neither of those updates have anything to do with this add-on.

**Comment by RacerEdge** [comment]
I tried a vm Backup of december the 6th.
It works without resetting the Box. I installed every update i‘ve been noted on.
So it looks like that it is depended on an update.
But i don‘t know which and what changed.

Regards

________________________________
Von: GimpArm ***@***.***>
Gesendet: Tuesday, December 19, 2023 6:11:04 PM
An: GimpArm/hassio-addons ***@***.***>
Cc: RacerEdge ***@***.***>; Author ***@***.***>
Betreff: Re: [GimpArm/hassio-addons] Now status sind update (Issue #5)


If you can control it then it is almost certainly the SmartFriends box not reporting the numbers. Check if it works in the official app. Try resetting it up in SmartFriends.

Neither of those updates have anything to do with this add-on.

**Comment by GimpArm** [comment]
Since this is an independent service written in dotnet that has no dependency on home assistant, these updates cannot possibly affect it. Those aren’t even changes to this code base. The data you posted showed the rollers at position 16, so it is reporting position. I suggest you look at how you are using that data in home assistant.

**Comment by RacerEdge** [comment]
I tried everthing.
But it doesn’t work anymore.
No status from the shutters and switches.
the configured switches are also not in the scenes that I configured and I cannot add them because they are not found in the system????

Any advise?

Thanks.

Von: GimpArm ***@***.***>
Antworten an: GimpArm/hassio-addons ***@***.***>
Datum: Dienstag, 19. Dezember 2023 um 20:25
An: GimpArm/hassio-addons ***@***.***>
Cc: RacerEdge ***@***.***>, Author ***@***.***>
Betreff: Re: [GimpArm/hassio-addons] Now status sind update (Issue #5)


Since this is an independent service written in dotnet that has no dependency on home assistant, these updates cannot possibly affect it. Those aren’t even changes to this code base. The data you posted showed the rollers at position 16, so it is reporting position. I suggest you look at how you are using that data in home assistant.

**Comment by GimpArm** [comment]
In the data you posted earlier, the blinds were listed at being in position 12. Was that correct? Do it again, is it correct? If the answer is “no” then you probably have to delete them from the official app and set them up again. If the answer is “yes” then you need to look at how you are parsing the data on Home Assistant. Maybe that part changed. This add-on literally just makes the raw data that the SmartFriends box gives to the official app available over a rest API. How you configure it to interpret the data is up to you.

**Comment by RacerEdge** [comment]
Hi,

happy new year. 😊

 

I follow your advise but I cannot do more than add a cover chart and select the entities.

In the terminal the position will changed when I 

In the log , no error.

 

What can I do to check the “parsing” in homeassistant?

 

Is there a tool that check my yaml-files and give a resoult?

 

I also check the release-notes and changes.

 

I found nothing☹

 

Am I to blind and am i the only one who use your fantastic add-one and have this issue?

 

Regards

 

 

 

 

Von: GimpArm ***@***.***>
Antworten an: GimpArm/hassio-addons ***@***.***>
Datum: Mittwoch, 27. Dezember 2023 um 21:51
An: GimpArm/hassio-addons ***@***.***>
Cc: RacerEdge ***@***.***>, Author ***@***.***>
Betreff: Re: [GimpArm/hassio-addons] Now status sind update (Issue #5)

 

In the data you posted earlier, the blinds were listed at being in position 12. Was that correct? Do it again, is it correct? If the answer is “no” then you probably have to delete them from the official app and set them up again. If the answer is “yes” then you need to look at how you are parsing the data on Home Assistant. Maybe that part changed. This add-on literally just makes the raw data that the SmartFriends box gives to the official app available over a rest API. How you configure it to interpret the data is up to you.

**Comment by RacerEdge** [comment]
Hi,
can you help me with this error message in the protocol of the schellenberg add on?

s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

Unhandled exception. Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: {. Path '[0]', line 8, position 1.

   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()


Thank you very much

Von: GimpArm ***@***.***>
Antworten an: GimpArm/hassio-addons ***@***.***>
Datum: Mittwoch, 27. Dezember 2023 um 21:51
An: GimpArm/hassio-addons ***@***.***>
Cc: RacerEdge ***@***.***>, Author ***@***.***>
Betreff: Re: [GimpArm/hassio-addons] Now status sind update (Issue #5)


In the data you posted earlier, the blinds were listed at being in position 12. Was that correct? Do it again, is it correct? If the answer is “no” then you probably have to delete them from the official app and set them up again. If the answer is “yes” then you need to look at how you are parsing the data on Home Assistant. Maybe that part changed. This add-on literally just makes the raw data that the SmartFriends box gives to the official app available over a rest API. How you configure it to interpret the data is up to you.

**Comment by Pacosar** [comment]
Same problem here. Managed to control the shutters via Rest-API today, but the position is not displayed. Via http://myIP:5001/get/19116/position/ I get the current status of the shutters displayed, somehow it is not transferred though.
Here my config:

shell_command:
    shutter_up:        "curl http://127.0.0.1:5001/set/{{ device_id }}/rollingShutter/up"
    shutter_down:      "curl http://127.0.0.1:5001/set/{{ device_id }}/rollingShutter/down"
    shutter_stop:      "curl http://127.0.0.1:5001/set/{{ device_id }}/rollingShutter/stop"
    shutter_position:  "curl http://127.0.0.1:5001/set/{{ device_id }}/position/{{ 100 - position }}"

sensor:
  - platform: command_line
    name: shutter_position_office
    command: "curl http://myIP:5001/get/19116/position/"
    unit_of_measurement: "%"
    scan_interval: 5
    value_template: '{{ 100 - value_json.currentValue }}'
    
cover:
  - platform: template
    covers:
      shutter_office:
        friendly_name: "Shutter - Office"
        device_class: shutter
        position_template: "{{ states('sensor.shutter_position_office') }}"
        open_cover:
          service: shell_command.shutter_up
          data:
            device_id: 19116
        close_cover:
          service: shell_command.shutter_down
          data:
            device_id: 19116
        stop_cover:
          service: shell_command.shutter_stop
          data:
            device_id: 19116
        set_cover_position:
          service: shell_command.shutter_position
          data_template:
            device_id: 19116
            position: "{{ position }}"

**Comment by RacerEdge** [comment]
Don‘t use REST API.
Take mqtt and it works.

I had the same problem.

**Comment by GimpArm** [comment]
Home Assistant changed their syntax for how do to a command line sensor. It is now the Command Line Integration https://www.home-assistant.io/integrations/command_line/
Please read the Home Assistant documentation for problems with Home Assistant.

Here is the updated syntax for the position sensor after I read the documentation linked to above.

```
command_line:
  - sensor:
      name: shutter_position_office
      command : 'curl http://127.0.0.1:5001/get/10433/position'
      unit_of_measurement: '%'
      scan_interval: 5
      value_template: '{{ 100 - value_json.currentValue }}'
```

**Comment by Pacosar** [comment]
Thank you very much, works fine.
