### ISSUE TITLE
SSL connection issues with version 3.11

### ISSUE THREAD

**Issue by l-k-r** [GimpArm/hassio-addons#7]
Hi there, 
I just installed version 3.11 in home assistant and got the following ssl errors when connecting to a SmartFriends box: 

s6-rc: info: service legacy-services successfully started
info: SmartFriends.Api.Session[0]
      Connecting to <IP-Address>
fail: SmartFriends.Api.Session[0]
      Failed to open socket to host
      System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
       ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
       ---> Interop+Crypto+OpenSslCryptographicException: error:0A0000B5:SSL routines::no ciphers available
         --- End of inner exception stack trace ---
         at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
         at System.Net.Security.SslStreamPal.HandshakeInternal(SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
         --- End of inner exception stack trace ---
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
         at SmartFriends.Api.Client.Open() in D:\Projects\smartfriends-bridge\source\SmartFriends.Api\Client.cs:line 70

Home assistant versions: 
Core 2024.2.2
Supervisor 2024.01.1
Operating System 11.5
Frontend 20240207.1

Config: 
CSymbol: D19033
CSymbolAddon: i
ShcVersion: 3.4.11
ShApiVersion: "3.3"

Is this a known bug or did I miss something in the installation?

**Comment by GimpArm** [comment]
That’s a new bug. What system are you running this on? I’m guessing a Raspberry Pi. I was forced to upgrade the Arm64 Debian base for the Arm64 but didn’t have a chance to test it. I was just hoping it would work. I’ll be able to fix it this week but for now just downgrade.

**Comment by l-k-r** [comment]
Yep, its a Raspberry Pi, os release shows: VERSION="11.5 (RaspberryPi 4 64bit)"

My best guess so far is, that openssl and dotnet are not compatible / allowing the cipher algorithm...

**Comment by GimpArm** [comment]
The bigger problem is the SmartFriends box uses insecure encryption and everyone is dropping support for it. Arm64 was the only platform I was forced to upgrade because there was a libc error, not even dotnet 8, just wasn’t possible for me to build it. I upgraded just that one and pushed without any testing. Sorry about that.

**Comment by l-k-r** [comment]
Don´t worry - all ok. I just downgraded to 3.10 and now the connection could be established.

**Comment by GimpArm** [comment]
I pushed a new version with everything fixed. It should be safe for you to update. If you run into another problem please open another issue.

**Comment by l-k-r** [comment]
Thanks for the fast fix! Now the connections can be established.
