### ISSUE TITLE
Entities unknown after Update to 3.12

### ISSUE THREAD

**Issue by ulrike-zar** [GimpArm/hassio-addons#8]
Hi,
I just updated to 3.12 but now all my entities are set to unknown. The protocol looks good, no errors, I use the REST-API. In the list (http://homeassistant:5001/list) I find all devices, e.g. the folowwing window:

  {
    "id": 13527,
    "name": "Fenster Bad EG",
    "room": "Bad",
    "gatewayDevice": "SmartFriendsBox",
    "kind": "DoorWindowContact",
    "manufacturer": "ABUS KG",
    "state": "Closed",
    "devices": {
      "doorWindowContact": {
        "Id": 2329,
        "description": "AbusDoorWindowNoc",
        "currentValue": "Closed"
      },
      "failureStatus": {
        "Id": 14423,
        "description": "AbusFailureDevice",
        "currentValue": "FailureNoFailure"
      }
    }
  },

Trying to get the data I use the following code in the configuration.yaml
- binary_sensor:
    name: Bad EG Fenster
    device_class: window
    command: "curl http://192.168.11.8:5001/get/13527"
    scan_interval: 5
    value_template: '{{ value_json.state }}'
    payload_on: 1
    payload_off: 0

But.... in the developer tools, the entity is displayed "unknown". Can you help me?

**Comment by ulrike-zar** [comment]
My configuration
![2024-02-26 19_44_55-Home Assistant](https://github.com/GimpArm/hassio-addons/assets/115952204/1b276d26-4e31-480b-a4d0-2cc272325c2b)

**Comment by GimpArm** [comment]
The failure status from the SmartFriends hub say “AbusFailureDevice”. I’m not exactly sure what that means but check that it works in the office app. This status comes from there.

**Comment by ulrike-zar** [comment]
Thank you for your quick answer! I just checked the Smart Friends App - everything ok:
![IMG_4770](https://github.com/GimpArm/hassio-addons/assets/115952204/d3b5db8c-caf9-4ddf-9006-1ece62a5eadb)
![IMG_4769](https://github.com/GimpArm/hassio-addons/assets/115952204/9159b91c-7022-4442-88bf-fcb146a9a38c)

**Comment by GimpArm** [comment]
Ok, I know now why people are having problems with the REST api. Home Assistant change their syntax for a command line sensor. I updated my examples in the documentation. Take a look here for more information https://www.home-assistant.io/integrations/command_line/

For your specific binary sensor it will probable be something like this
```
command_line:
  - binary_sensor:
      name: Bad EG Fenster
      device_class: window
      command : 'curl http://192.168.11.8:5001/get/13527'
      scan_interval: 5
      value_template: '{{ value_json.state }}'
      payload_on: Opened
      payload_off: Closed
```

**Comment by ulrike-zar** [comment]
Hi, I've also been testing and looking what my problem is: 
I had already changed the command line integration to the new syntax but.... my payload_on and payload_off was false. In your example , it is already corrected; payload_on must be "Opened" ans payload_off must be "Closed" - before I had 1 and 0. I wonder how it worked before but now I'm happy that everythin is fine again.

Thank you very much for your support and have a wonderful sunday!
