### ISSUE TITLE
HSV color not working

### ISSUE THREAD

**Issue by dietzi** [GimpArm/hassio-addons#9]
I have a device which uses hsv for color. MQTT doesn't recognize the commands. Only integers are accepted and changed. I don't know how to change the hsv value. Is this a bug?
![17183662487805682240584497477984](https://github.com/GimpArm/hassio-addons/assets/10375119/725d540d-6c66-488e-9898-0364839b8269)

Changing the value with URL works fine. http://127.0.0.1:5001/set/5840/hsv/100,100,100

**Comment by GimpArm** [comment]
Probably a bug since I don’t have any hsv devices myself. I’ll take a look as soon as I can. I’ll probably need you to test if you want it fixed.

**Comment by GimpArm** [comment]
So I just wasn't looking for it at all so it wasn't handling the response. I pushed a new version that will parse the HSV values.
